################数据源与德鲁伊配置################
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ylsdd?tinyInt1isBit=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    ###################### Druid配置#################################
    #通过 http://domain:port/druid/login.html 访问druid监控页面
    druid:
      initialSize: 10    #初始化时建立物理连接的个数
      maxActive: 20     #最大连接池数量
      minIdle: 5        #最小连接池数量
      maxWait: 60000    # 配置获取连接等待超时的时间
      timeBetweenEvictionRunsMillis: 60000    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000      # 配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: SELECT 1 FROM DUAL     #用来检测连接是否有效的sql，要求是一个查询语句
      testWhileIdle: true   #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效.建议配置为true，不影响性能，并且保证安全性
      testOnBorrow: false   #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnReturn: false    #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      filters: stat,wall,log4j,config    #配置监控统计拦截的filters，去掉后监控界面sql无法统计.属性类型是字符串，常用的插件有：监控统计用的filter:stat 日志用的filter:log4j 防御sql注入的filter:wall
        #filter:
        #stat:
          #log-slow-sql: true
      connection-properties: config.decrypt=false #密码加密

################Mybatis配置################
mybatis:
  mapper-locations:  classpath:mybatis/mapper/*.xml
  configuration:
    #使用日志
    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl
    #使全局的映射器启用或禁用缓存
    cache-enabled: true                                 
    #全局启用或禁用延迟加载。当禁用时，所有关联对象都会即时加载
    lazy-loading-enabled: true
    #当启用时，有延迟加载属性的对象在被调用时将会完全加载任意属性。否则，每种属性将会按需要加载
    aggressive-lazy-loading: true
    #是否允许单条sql 返回多个数据集  (取决于驱动的兼容性) default:true                                           
    multiple-result-sets-enabled: true
    #是否允许单条sql 返回多个数据集  (取决于驱动的兼容性) default:true
    use-column-label: true
    #允许JDBC 生成主键。需要驱动器支持。如果设为了true，这个设置将强制使用被生成的主键，有一些驱动器不兼容不过仍然可以执行。  default:false
    use-generated-keys: true
    #指定 MyBatis 如何自动映射 数据基表的列 NONE：不映射　PARTIAL:部分  FULL:全部
    auto-mapping-behavior: partial
    #这是默认的执行类型  （SIMPLE: 简单； REUSE: 执行器可能重复使用prepared statements语句；BATCH: 执行器可以重复执行语句和批量更新）
    default-executor-type: simple
    #使用驼峰命名法转换字段
    map-underscore-to-camel-case: true
    #设置本地缓存范围 session:就会有数据的共享  statement:语句范围 (多个SqlSession或者分布式的环境下使用，避免脏读 ) defalut:session
    local-cache-scope: session
    #设置但JDBC类型为空时,某些驱动程序 要指定值,default:OTHER，插入空值时不需要指定类型
    jdbc-type-for-null: null

##############集成Generator###############